name: Deploy via SCP

on:
  push:
    branches:
      - main  # Déclenchement sur la branche principale

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up SSH key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SFTP_PRIVATE_KEY }}  # Utilise ta clé privée stockée dans les secrets GitHub

      - name: Upload files via SCP
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SFTP_HOST }}  # Remplacer par un secret ou une variable définie
          username: ${{ secrets.SFTP_USER }}  # Remplacer par un secret ou une variable définie
          port: 2022
          source: "./*"  # Fichiers à envoyer
          target: "/cogs/"  # Dossier distant
          key: ${{ secrets.SFTP_PRIVATE_KEY }}  # Assure-toi que la clé privée est également utilisée ici
          overwrite: true
          timeout: 30s
          debug: true  # Active le mode debug pour des logs détaillés
