name: Deploy via SCP

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Upload files via SCP (no tar)
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ vars.SFTP_HOST }}
          username: ${{ vars.SFTP_USER }}
          password: ${{ secrets.SFTP_PASS }}
          port: 2022
          source: "./*"  # Envoie les fichiers un par un sans tar
          target: "~/cogs/"
          overwrite: true
          timeout: 30s
